// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADfDxzQChIc7IruY-chQkmKm296gOSw4',
    appId: '1:537954318009:web:eff2d7a3f7e6660e9f8d68',
    messagingSenderId: '537954318009',
    projectId: 'playing-tracker-app',
    authDomain: 'playing-tracker-app.firebaseapp.com',
    storageBucket: 'playing-tracker-app.firebasestorage.app',
    measurementId: 'G-TBX67P20SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIf0IET1Qd10g36do2oMKI9vKJ0gwwDI',
    appId: '1:537954318009:android:35845aaeaf3eeaf89f8d68',
    messagingSenderId: '537954318009',
    projectId: 'playing-tracker-app',
    storageBucket: 'playing-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOdLKboyT0C8SkL2kuR6snWoYWezQSBQ',
    appId: '1:537954318009:ios:36f47ece6fe9a0d59f8d68',
    messagingSenderId: '537954318009',
    projectId: 'playing-tracker-app',
    storageBucket: 'playing-tracker-app.firebasestorage.app',
    iosBundleId: 'com.gabriom.playingtrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOdLKboyT0C8SkL2kuR6snWoYWezQSBQ',
    appId: '1:537954318009:ios:36f47ece6fe9a0d59f8d68',
    messagingSenderId: '537954318009',
    projectId: 'playing-tracker-app',
    storageBucket: 'playing-tracker-app.firebasestorage.app',
    iosBundleId: 'com.gabriom.playingtrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDADfDxzQChIc7IruY-chQkmKm296gOSw4',
    appId: '1:537954318009:web:0e32d5bb498bf5db9f8d68',
    messagingSenderId: '537954318009',
    projectId: 'playing-tracker-app',
    authDomain: 'playing-tracker-app.firebaseapp.com',
    storageBucket: 'playing-tracker-app.firebasestorage.app',
    measurementId: 'G-Z2P13CZFVV',
  );
}
